# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ranger_msgs/ActuatorState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ranger_msgs.msg

class ActuatorState(genpy.Message):
  _md5sum = "ac625266ba0e0f3a4c2bd178030b5daf"
  _type = "ranger_msgs/ActuatorState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 id
MotorState motor
DriverState driver

================================================================================
MSG: ranger_msgs/MotorState
int32 rpm
float32 current
int32 pulse_count
================================================================================
MSG: ranger_msgs/DriverState
float32 driver_voltage
float32 driver_temperature
float32 motor_temperature
uint32 driver_state
"""
  __slots__ = ['id','motor','driver']
  _slot_types = ['uint32','ranger_msgs/MotorState','ranger_msgs/DriverState']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,motor,driver

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ActuatorState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.motor is None:
        self.motor = ranger_msgs.msg.MotorState()
      if self.driver is None:
        self.driver = ranger_msgs.msg.DriverState()
    else:
      self.id = 0
      self.motor = ranger_msgs.msg.MotorState()
      self.driver = ranger_msgs.msg.DriverState()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Iifi3fI().pack(_x.id, _x.motor.rpm, _x.motor.current, _x.motor.pulse_count, _x.driver.driver_voltage, _x.driver.driver_temperature, _x.driver.motor_temperature, _x.driver.driver_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.motor is None:
        self.motor = ranger_msgs.msg.MotorState()
      if self.driver is None:
        self.driver = ranger_msgs.msg.DriverState()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.id, _x.motor.rpm, _x.motor.current, _x.motor.pulse_count, _x.driver.driver_voltage, _x.driver.driver_temperature, _x.driver.motor_temperature, _x.driver.driver_state,) = _get_struct_Iifi3fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Iifi3fI().pack(_x.id, _x.motor.rpm, _x.motor.current, _x.motor.pulse_count, _x.driver.driver_voltage, _x.driver.driver_temperature, _x.driver.motor_temperature, _x.driver.driver_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.motor is None:
        self.motor = ranger_msgs.msg.MotorState()
      if self.driver is None:
        self.driver = ranger_msgs.msg.DriverState()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.id, _x.motor.rpm, _x.motor.current, _x.motor.pulse_count, _x.driver.driver_voltage, _x.driver.driver_temperature, _x.driver.motor_temperature, _x.driver.driver_state,) = _get_struct_Iifi3fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Iifi3fI = None
def _get_struct_Iifi3fI():
    global _struct_Iifi3fI
    if _struct_Iifi3fI is None:
        _struct_Iifi3fI = struct.Struct("<Iifi3fI")
    return _struct_Iifi3fI
