# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ranger_msgs/ActuatorStateArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ranger_msgs.msg
import std_msgs.msg

class ActuatorStateArray(genpy.Message):
  _md5sum = "c27e592efdd1087f3e73e2d4f7935864"
  _type = "ranger_msgs/ActuatorStateArray"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

ActuatorState[] states
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: ranger_msgs/ActuatorState
uint32 id
MotorState motor
DriverState driver

================================================================================
MSG: ranger_msgs/MotorState
int32 rpm
float32 current
int32 pulse_count
================================================================================
MSG: ranger_msgs/DriverState
float32 driver_voltage
float32 driver_temperature
float32 motor_temperature
uint32 driver_state
"""
  __slots__ = ['header','states']
  _slot_types = ['std_msgs/Header','ranger_msgs/ActuatorState[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,states

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ActuatorStateArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.states is None:
        self.states = []
    else:
      self.header = std_msgs.msg.Header()
      self.states = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.states)
      buff.write(_struct_I.pack(length))
      for val1 in self.states:
        _x = val1.id
        buff.write(_get_struct_I().pack(_x))
        _v1 = val1.motor
        _x = _v1
        buff.write(_get_struct_ifi().pack(_x.rpm, _x.current, _x.pulse_count))
        _v2 = val1.driver
        _x = _v2
        buff.write(_get_struct_3fI().pack(_x.driver_voltage, _x.driver_temperature, _x.motor_temperature, _x.driver_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.states is None:
        self.states = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.states = []
      for i in range(0, length):
        val1 = ranger_msgs.msg.ActuatorState()
        start = end
        end += 4
        (val1.id,) = _get_struct_I().unpack(str[start:end])
        _v3 = val1.motor
        _x = _v3
        start = end
        end += 12
        (_x.rpm, _x.current, _x.pulse_count,) = _get_struct_ifi().unpack(str[start:end])
        _v4 = val1.driver
        _x = _v4
        start = end
        end += 16
        (_x.driver_voltage, _x.driver_temperature, _x.motor_temperature, _x.driver_state,) = _get_struct_3fI().unpack(str[start:end])
        self.states.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.states)
      buff.write(_struct_I.pack(length))
      for val1 in self.states:
        _x = val1.id
        buff.write(_get_struct_I().pack(_x))
        _v5 = val1.motor
        _x = _v5
        buff.write(_get_struct_ifi().pack(_x.rpm, _x.current, _x.pulse_count))
        _v6 = val1.driver
        _x = _v6
        buff.write(_get_struct_3fI().pack(_x.driver_voltage, _x.driver_temperature, _x.motor_temperature, _x.driver_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.states is None:
        self.states = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.states = []
      for i in range(0, length):
        val1 = ranger_msgs.msg.ActuatorState()
        start = end
        end += 4
        (val1.id,) = _get_struct_I().unpack(str[start:end])
        _v7 = val1.motor
        _x = _v7
        start = end
        end += 12
        (_x.rpm, _x.current, _x.pulse_count,) = _get_struct_ifi().unpack(str[start:end])
        _v8 = val1.driver
        _x = _v8
        start = end
        end += 16
        (_x.driver_voltage, _x.driver_temperature, _x.motor_temperature, _x.driver_state,) = _get_struct_3fI().unpack(str[start:end])
        self.states.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3fI = None
def _get_struct_3fI():
    global _struct_3fI
    if _struct_3fI is None:
        _struct_3fI = struct.Struct("<3fI")
    return _struct_3fI
_struct_ifi = None
def _get_struct_ifi():
    global _struct_ifi
    if _struct_ifi is None:
        _struct_ifi = struct.Struct("<ifi")
    return _struct_ifi
