# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ranger_msgs/DriverState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DriverState(genpy.Message):
  _md5sum = "e5e7f5fd1e7cc0bd7398225868b7037f"
  _type = "ranger_msgs/DriverState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 driver_voltage
float32 driver_temperature
float32 motor_temperature
uint32 driver_state
"""
  __slots__ = ['driver_voltage','driver_temperature','motor_temperature','driver_state']
  _slot_types = ['float32','float32','float32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       driver_voltage,driver_temperature,motor_temperature,driver_state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DriverState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.driver_voltage is None:
        self.driver_voltage = 0.
      if self.driver_temperature is None:
        self.driver_temperature = 0.
      if self.motor_temperature is None:
        self.motor_temperature = 0.
      if self.driver_state is None:
        self.driver_state = 0
    else:
      self.driver_voltage = 0.
      self.driver_temperature = 0.
      self.motor_temperature = 0.
      self.driver_state = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3fI().pack(_x.driver_voltage, _x.driver_temperature, _x.motor_temperature, _x.driver_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.driver_voltage, _x.driver_temperature, _x.motor_temperature, _x.driver_state,) = _get_struct_3fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3fI().pack(_x.driver_voltage, _x.driver_temperature, _x.motor_temperature, _x.driver_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.driver_voltage, _x.driver_temperature, _x.motor_temperature, _x.driver_state,) = _get_struct_3fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3fI = None
def _get_struct_3fI():
    global _struct_3fI
    if _struct_3fI is None:
        _struct_3fI = struct.Struct("<3fI")
    return _struct_3fI
