// Generated by gencpp from file ranger_msgs/RangerLightCmd.msg
// DO NOT EDIT!


#ifndef RANGER_MSGS_MESSAGE_RANGERLIGHTCMD_H
#define RANGER_MSGS_MESSAGE_RANGERLIGHTCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ranger_msgs
{
template <class ContainerAllocator>
struct RangerLightCmd_
{
  typedef RangerLightCmd_<ContainerAllocator> Type;

  RangerLightCmd_()
    : enable_cmd_light_control(false)
    , front_mode(0)  {
    }
  RangerLightCmd_(const ContainerAllocator& _alloc)
    : enable_cmd_light_control(false)
    , front_mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _enable_cmd_light_control_type;
  _enable_cmd_light_control_type enable_cmd_light_control;

   typedef uint8_t _front_mode_type;
  _front_mode_type front_mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(LIGHT_CONST_OFF)
  #undef LIGHT_CONST_OFF
#endif
#if defined(_WIN32) && defined(LIGHT_CONST_ON)
  #undef LIGHT_CONST_ON
#endif

  enum {
    LIGHT_CONST_OFF = 0u,
    LIGHT_CONST_ON = 1u,
  };


  typedef boost::shared_ptr< ::ranger_msgs::RangerLightCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ranger_msgs::RangerLightCmd_<ContainerAllocator> const> ConstPtr;

}; // struct RangerLightCmd_

typedef ::ranger_msgs::RangerLightCmd_<std::allocator<void> > RangerLightCmd;

typedef boost::shared_ptr< ::ranger_msgs::RangerLightCmd > RangerLightCmdPtr;
typedef boost::shared_ptr< ::ranger_msgs::RangerLightCmd const> RangerLightCmdConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ranger_msgs::RangerLightCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ranger_msgs::RangerLightCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ranger_msgs::RangerLightCmd_<ContainerAllocator1> & lhs, const ::ranger_msgs::RangerLightCmd_<ContainerAllocator2> & rhs)
{
  return lhs.enable_cmd_light_control == rhs.enable_cmd_light_control &&
    lhs.front_mode == rhs.front_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ranger_msgs::RangerLightCmd_<ContainerAllocator1> & lhs, const ::ranger_msgs::RangerLightCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ranger_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ranger_msgs::RangerLightCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ranger_msgs::RangerLightCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ranger_msgs::RangerLightCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ranger_msgs::RangerLightCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ranger_msgs::RangerLightCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ranger_msgs::RangerLightCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ranger_msgs::RangerLightCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3966761cbe75536bce0bd8e18f517d6e";
  }

  static const char* value(const ::ranger_msgs::RangerLightCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3966761cbe75536bULL;
  static const uint64_t static_value2 = 0xce0bd8e18f517d6eULL;
};

template<class ContainerAllocator>
struct DataType< ::ranger_msgs::RangerLightCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ranger_msgs/RangerLightCmd";
  }

  static const char* value(const ::ranger_msgs::RangerLightCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ranger_msgs::RangerLightCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 LIGHT_CONST_OFF = 0\n"
"uint8 LIGHT_CONST_ON = 1\n"
"\n"
"bool enable_cmd_light_control\n"
"uint8 front_mode\n"
;
  }

  static const char* value(const ::ranger_msgs::RangerLightCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ranger_msgs::RangerLightCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable_cmd_light_control);
      stream.next(m.front_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RangerLightCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ranger_msgs::RangerLightCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ranger_msgs::RangerLightCmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "enable_cmd_light_control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_cmd_light_control);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "front_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.front_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RANGER_MSGS_MESSAGE_RANGERLIGHTCMD_H
