// Generated by gencpp from file ranger_msgs/TriggerParkMode.msg
// DO NOT EDIT!


#ifndef RANGER_MSGS_MESSAGE_TRIGGERPARKMODE_H
#define RANGER_MSGS_MESSAGE_TRIGGERPARKMODE_H

#include <ros/service_traits.h>


#include <ranger_msgs/TriggerParkModeRequest.h>
#include <ranger_msgs/TriggerParkModeResponse.h>


namespace ranger_msgs
{

struct TriggerParkMode
{

typedef TriggerParkModeRequest Request;
typedef TriggerParkModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TriggerParkMode
} // namespace ranger_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ranger_msgs::TriggerParkMode > {
  static const char* value()
  {
    return "9f41a9b02f1e542a8142cc751052f35f";
  }

  static const char* value(const ::ranger_msgs::TriggerParkMode&) { return value(); }
};

template<>
struct DataType< ::ranger_msgs::TriggerParkMode > {
  static const char* value()
  {
    return "ranger_msgs/TriggerParkMode";
  }

  static const char* value(const ::ranger_msgs::TriggerParkMode&) { return value(); }
};


// service_traits::MD5Sum< ::ranger_msgs::TriggerParkModeRequest> should match
// service_traits::MD5Sum< ::ranger_msgs::TriggerParkMode >
template<>
struct MD5Sum< ::ranger_msgs::TriggerParkModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ranger_msgs::TriggerParkMode >::value();
  }
  static const char* value(const ::ranger_msgs::TriggerParkModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ranger_msgs::TriggerParkModeRequest> should match
// service_traits::DataType< ::ranger_msgs::TriggerParkMode >
template<>
struct DataType< ::ranger_msgs::TriggerParkModeRequest>
{
  static const char* value()
  {
    return DataType< ::ranger_msgs::TriggerParkMode >::value();
  }
  static const char* value(const ::ranger_msgs::TriggerParkModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ranger_msgs::TriggerParkModeResponse> should match
// service_traits::MD5Sum< ::ranger_msgs::TriggerParkMode >
template<>
struct MD5Sum< ::ranger_msgs::TriggerParkModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ranger_msgs::TriggerParkMode >::value();
  }
  static const char* value(const ::ranger_msgs::TriggerParkModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ranger_msgs::TriggerParkModeResponse> should match
// service_traits::DataType< ::ranger_msgs::TriggerParkMode >
template<>
struct DataType< ::ranger_msgs::TriggerParkModeResponse>
{
  static const char* value()
  {
    return DataType< ::ranger_msgs::TriggerParkMode >::value();
  }
  static const char* value(const ::ranger_msgs::TriggerParkModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RANGER_MSGS_MESSAGE_TRIGGERPARKMODE_H
