// Generated by gencpp from file ranger_msgs/TriggerParkModeRequest.msg
// DO NOT EDIT!


#ifndef RANGER_MSGS_MESSAGE_TRIGGERPARKMODEREQUEST_H
#define RANGER_MSGS_MESSAGE_TRIGGERPARKMODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ranger_msgs
{
template <class ContainerAllocator>
struct TriggerParkModeRequest_
{
  typedef TriggerParkModeRequest_<ContainerAllocator> Type;

  TriggerParkModeRequest_()
    : TriggerParkedMode(false)  {
    }
  TriggerParkModeRequest_(const ContainerAllocator& _alloc)
    : TriggerParkedMode(false)  {
  (void)_alloc;
    }



   typedef uint8_t _TriggerParkedMode_type;
  _TriggerParkedMode_type TriggerParkedMode;





  typedef boost::shared_ptr< ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TriggerParkModeRequest_

typedef ::ranger_msgs::TriggerParkModeRequest_<std::allocator<void> > TriggerParkModeRequest;

typedef boost::shared_ptr< ::ranger_msgs::TriggerParkModeRequest > TriggerParkModeRequestPtr;
typedef boost::shared_ptr< ::ranger_msgs::TriggerParkModeRequest const> TriggerParkModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator1> & lhs, const ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.TriggerParkedMode == rhs.TriggerParkedMode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator1> & lhs, const ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ranger_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1df76e295341440f94dfcd5d6bc2a3c2";
  }

  static const char* value(const ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1df76e295341440fULL;
  static const uint64_t static_value2 = 0x94dfcd5d6bc2a3c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ranger_msgs/TriggerParkModeRequest";
  }

  static const char* value(const ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool TriggerParkedMode\n"
;
  }

  static const char* value(const ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.TriggerParkedMode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TriggerParkModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ranger_msgs::TriggerParkModeRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "TriggerParkedMode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.TriggerParkedMode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RANGER_MSGS_MESSAGE_TRIGGERPARKMODEREQUEST_H
