// Generated by gencpp from file ranger_msgs/TriggerParkModeResponse.msg
// DO NOT EDIT!


#ifndef RANGER_MSGS_MESSAGE_TRIGGERPARKMODERESPONSE_H
#define RANGER_MSGS_MESSAGE_TRIGGERPARKMODERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ranger_msgs
{
template <class ContainerAllocator>
struct TriggerParkModeResponse_
{
  typedef TriggerParkModeResponse_<ContainerAllocator> Type;

  TriggerParkModeResponse_()
    : isParked(false)  {
    }
  TriggerParkModeResponse_(const ContainerAllocator& _alloc)
    : isParked(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isParked_type;
  _isParked_type isParked;





  typedef boost::shared_ptr< ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TriggerParkModeResponse_

typedef ::ranger_msgs::TriggerParkModeResponse_<std::allocator<void> > TriggerParkModeResponse;

typedef boost::shared_ptr< ::ranger_msgs::TriggerParkModeResponse > TriggerParkModeResponsePtr;
typedef boost::shared_ptr< ::ranger_msgs::TriggerParkModeResponse const> TriggerParkModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator1> & lhs, const ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.isParked == rhs.isParked;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator1> & lhs, const ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ranger_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f58cae7bebf796fbbfd63f3ba9b50242";
  }

  static const char* value(const ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf58cae7bebf796fbULL;
  static const uint64_t static_value2 = 0xbfd63f3ba9b50242ULL;
};

template<class ContainerAllocator>
struct DataType< ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ranger_msgs/TriggerParkModeResponse";
  }

  static const char* value(const ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isParked\n"
;
  }

  static const char* value(const ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isParked);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TriggerParkModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ranger_msgs::TriggerParkModeResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "isParked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isParked);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RANGER_MSGS_MESSAGE_TRIGGERPARKMODERESPONSE_H
