(cl:defpackage ranger_msgs-msg
  (:use )
  (:export
   "<ACTUATORSTATE>"
   "ACTUATORSTATE"
   "<ACTUATORSTATEARRAY>"
   "ACTUATORSTATEARRAY"
   "<BATTERYSTATE>"
   "BATTERYSTATE"
   "<DRIVERSTATE>"
   "DRIVERSTATE"
   "<MOTIONSTATE>"
   "MOTIONSTATE"
   "<MOTORSTATE>"
   "MOTORSTATE"
   "<RANGERLIGHTCMD>"
   "RANGERLIGHTCMD"
   "<RSSTATUS>"
   "RSSTATUS"
   "<SYSTEMSTATE>"
   "SYSTEMSTATE"
  ))

