(cl:in-package ranger_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SEQ-VAL
          SEQ
          STAMP-VAL
          STAMP
          FRAME_ID-VAL
          FRAME_ID
          VOLTAGE-VAL
          VOLTAGE
          TEMPERATURE-VAL
          TEMPERATURE
          CURRENT-VAL
          CURRENT
          CHARGE-VAL
          CHARGE
          CAPACITY-VAL
          CAPACITY
          DESIGN_CAPACITY-VAL
          DESIGN_CAPACITY
          PERCENTAGE-VAL
          PERCENTAGE
          POWER_SUPPLY_STATUS-VAL
          POWER_SUPPLY_STATUS
          POWER_SUPPLY_HEALTH-VAL
          POWER_SUPPLY_HEALTH
          POWER_SUPPLY_TECHNOLOGY-VAL
          POWER_SUPPLY_TECHNOLOGY
          PRESENT-VAL
          PRESENT
))